name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern
  GraphQL client to one easy to use package.
version: 1.1.1-beta.3
authors:
- Eus Dima <eus@zinoapp.com>
- Zino Hofmann <zino@zinoapp.com>
- Michael Joseph Rosenthal <rosenthalm93@gmail.com>
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter
dependencies:
  graphql: ^1.1.1-beta.3
  flutter:
    sdk: flutter
  meta: ^1.1.6
  path: ^1.6.2
  path_provider: ^1.1.0
  rxdart: ^0.22.0
dev_dependencies:
  pedantic: <=1.7.99
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.5.3
environment:
<<<<<<< HEAD
  sdk: '>=2.1.0 <3.0.0'
dependency_overrides:
 graphql:
   path: ../graphql
=======
  sdk: '>=2.2.0 <3.0.0'
>>>>>>> 4fa6c5742778b89e839d81498c0350f6627e737d
